package org.opennaas.extensions.idb.serviceinterface.topology;

import org.apache.muse.core.AbstractCapability;
import org.w3c.dom.Element;

/**
 * topology server.
 *
 * TopologyWS.java
 * Sat May 05 19:53:17 CEST 2012
 * Generated by the Apache Muse Code Generation Tool
 */
 public class TopologyWS extends AbstractCapability implements ITopologyWS {
    /**
     * addEndpoint Handler.
     *
     * @param addEndpoint Request
     * @return addEndpoint Response
     * @throws Exception In case of errors
     */
    public Element addEndpoint (final Element addEndpoint)
             throws Exception {
        return CommonTopologyHandler.getInstance().handle("addEndpoint", addEndpoint);
    }

    /**
     * getDomains Handler.
     *
     * @param getDomains Request
     * @return getDomains Response
     * @throws Exception In case of errors
     */
    public Element getDomains (final Element getDomains)
             throws Exception {
        return CommonTopologyHandler.getInstance().handle("getDomains", getDomains);
    }

    /**
     * getEndpoints Handler.
     *
     * @param getEndpoints Request
     * @return getEndpoints Response
     * @throws Exception In case of errors
     */
    public Element getEndpoints (final Element getEndpoints)
             throws Exception {
        return CommonTopologyHandler.getInstance().handle("getEndpoints", getEndpoints);
    }

    /**
     * deleteDomain Handler.
     *
     * @param deleteDomain Request
     * @return deleteDomain Response
     * @throws Exception In case of errors
     */
    public Element deleteDomain (final Element deleteDomain)
             throws Exception {
        return CommonTopologyHandler.getInstance().handle("deleteDomain", deleteDomain);
    }

    /**
     * deleteLink Handler.
     *
     * @param deleteLink Request
     * @return deleteLink Response
     * @throws Exception In case of errors
     */
    public Element deleteLink (final Element deleteLink)
             throws Exception {
        return CommonTopologyHandler.getInstance().handle("deleteLink", deleteLink);
    }

    /**
     * deleteEndpoint Handler.
     *
     * @param deleteEndpoint Request
     * @return deleteEndpoint Response
     * @throws Exception In case of errors
     */
    public Element deleteEndpoint (final Element deleteEndpoint)
             throws Exception {
        return CommonTopologyHandler.getInstance().handle("deleteEndpoint", deleteEndpoint);
    }

    /**
     * getLinks Handler.
     *
     * @param getLinks Request
     * @return getLinks Response
     * @throws Exception In case of errors
     */
    public Element getLinks (final Element getLinks)
             throws Exception {
        return CommonTopologyHandler.getInstance().handle("getLinks", getLinks);
    }

    /**
     * addOrEditDomain Handler.
     *
     * @param addOrEditDomain Request
     * @return addOrEditDomain Response
     * @throws Exception In case of errors
     */
    public Element addOrEditDomain (final Element addOrEditDomain)
             throws Exception {
        return CommonTopologyHandler.getInstance().handle("addOrEditDomain", addOrEditDomain);
    }

    /**
     * addLink Handler.
     *
     * @param addLink Request
     * @return addLink Response
     * @throws Exception In case of errors
     */
    public Element addLink (final Element addLink)
             throws Exception {
        return CommonTopologyHandler.getInstance().handle("addLink", addLink);
    }

    /**
     * addDomain Handler.
     *
     * @param addDomain Request
     * @return addDomain Response
     * @throws Exception In case of errors
     */
    public Element addDomain (final Element addDomain)
             throws Exception {
        return CommonTopologyHandler.getInstance().handle("addDomain", addDomain);
    }

    /**
     * editLink Handler.
     *
     * @param editLink Request
     * @return editLink Response
     * @throws Exception In case of errors
     */
    public Element editLink (final Element editLink)
             throws Exception {
        return CommonTopologyHandler.getInstance().handle("editLink", editLink);
    }

    /**
     * editEndpoint Handler.
     *
     * @param editEndpoint Request
     * @return editEndpoint Response
     * @throws Exception In case of errors
     */
    public Element editEndpoint (final Element editEndpoint)
             throws Exception {
        return CommonTopologyHandler.getInstance().handle("editEndpoint", editEndpoint);
    }

    /**
     * editDomain Handler.
     *
     * @param editDomain Request
     * @return editDomain Response
     * @throws Exception In case of errors
     */
    public Element editDomain (final Element editDomain)
             throws Exception {
        return CommonTopologyHandler.getInstance().handle("editDomain", editDomain);
    }

}