package org.opennaas.extensions.idb.serviceinterface.notification;

import org.w3c.dom.Element;
import org.apache.muse.ws.addressing.soap.SoapFault;

/**
 * notification client.
 *
 * INotificationClient.java
 * Mon May 14 14:21:28 CEST 2012
 * Generated by the Apache Muse Code Generation Tool
 */
 public interface INotificationClient {


    /**
     * removeTopic Handler.
     *
     * @param removeTopic Request
     * @return removeTopic Response
     * @throws SoapFault In case of errors
     */
     Element removeTopic (Element removeTopic)
            throws SoapFault;


    /**
     * addTopic Handler.
     *
     * @param addTopic Request
     * @return addTopic Response
     * @throws SoapFault In case of errors
     */
     Element addTopic (Element addTopic)
            throws SoapFault;


    /**
     * subscribe Handler.
     *
     * @param subscribe Request
     * @return subscribe Response
     * @throws SoapFault In case of errors
     */
     Element subscribe (Element subscribe)
            throws SoapFault;


    /**
     * unsubscribe Handler.
     *
     * @param unsubscribe Request
     * @return unsubscribe Response
     * @throws SoapFault In case of errors
     */
     Element unsubscribe (Element unsubscribe)
            throws SoapFault;


    /**
     * getTopics Handler.
     *
     * @param getTopics Request
     * @return getTopics Response
     * @throws SoapFault In case of errors
     */
     Element getTopics (Element getTopics)
            throws SoapFault;


    /**
     * publish Handler.
     *
     * @param publish Request
     * @return publish Response
     * @throws SoapFault In case of errors
     */
     Element publish (Element publish)
            throws SoapFault;


}
