/**
 *  This code is part of the Harmony System implemented in Work Package 1 
 *  of the Phosphorus project. This work is supported by the European 
 *  Comission under the Sixth Framework Programme with contract number 
 *  IST-034115.
 *
 *  Copyright (C) 2006-2009 Phosphorus WP1 partners. Phosphorus Consortium.
 *  http://ist-phosphorus.eu/
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */

package org.opennaas.extensions.idb.da.dummy.webservice;

import org.opennaas.extensions.idb.da.dummy.handler.NotificationHandler;
import org.opennaas.extensions.idb.serviceinterface.databinding.jaxb.AddTopicResponseType;
import org.opennaas.extensions.idb.serviceinterface.databinding.jaxb.AddTopicType;
import org.opennaas.extensions.idb.serviceinterface.databinding.jaxb.GetTopicsResponseType;
import org.opennaas.extensions.idb.serviceinterface.databinding.jaxb.GetTopicsType;
import org.opennaas.extensions.idb.serviceinterface.databinding.jaxb.NetworkNotificationPortType;
import org.opennaas.extensions.idb.serviceinterface.databinding.jaxb.PublishResponseType;
import org.opennaas.extensions.idb.serviceinterface.databinding.jaxb.PublishType;
import org.opennaas.extensions.idb.serviceinterface.databinding.jaxb.RemoveTopicResponseType;
import org.opennaas.extensions.idb.serviceinterface.databinding.jaxb.RemoveTopicType;
import org.opennaas.extensions.idb.serviceinterface.databinding.jaxb.SubscribeResponseType;
import org.opennaas.extensions.idb.serviceinterface.databinding.jaxb.SubscribeType;
import org.opennaas.extensions.idb.serviceinterface.databinding.jaxb.TopicNotFoundFault_Exception;
import org.opennaas.extensions.idb.serviceinterface.databinding.jaxb.UnsubscribeResponseType;
import org.opennaas.extensions.idb.serviceinterface.databinding.jaxb.UnsubscribeType;

/**
 * nrpsDummyTopology server. MyCapability.java Thu Jun 26 10:38:49 CEST 2008
 * Generated by the Apache Muse Code Generation Tool
 */
public final class NotificationWS implements NetworkNotificationPortType {

	@Override
	public GetTopicsResponseType getTopics(GetTopicsType getTopics) {

		return NotificationHandler.getInstance().getTopics(getTopics);

	}

	@Override
	public PublishResponseType publish(PublishType publish)
			throws TopicNotFoundFault_Exception {

		return NotificationHandler.getInstance().publish(publish);

	}

	@Override
	public UnsubscribeResponseType unsubscribe(UnsubscribeType unsubscribe)
			throws TopicNotFoundFault_Exception {

		return NotificationHandler.getInstance().unsubscribe(unsubscribe);

	}

	@Override
	public AddTopicResponseType addTopic(AddTopicType addTopic) {

		return NotificationHandler.getInstance().addTopic(addTopic);

	}

	@Override
	public SubscribeResponseType subscribe(SubscribeType subscribe)
			throws TopicNotFoundFault_Exception {

		return NotificationHandler.getInstance().subscribe(subscribe);

	}

	@Override
	public RemoveTopicResponseType removeTopic(RemoveTopicType removeTopic) {

		return NotificationHandler.getInstance().removeTopic(removeTopic);

	}

}