package org.opennaas.extensions.idb.serviceinterface.topology;

import org.w3c.dom.Element;
import org.apache.muse.ws.addressing.soap.SoapFault;

/**
 * topology client.
 *
 * ITopologyClient.java
 * Fri May 04 16:27:14 CEST 2012
 * Generated by the Apache Muse Code Generation Tool
 */
 public interface ITopologyClient {


    /**
     * editLink Handler.
     *
     * @param editLink Request
     * @return editLink Response
     * @throws SoapFault In case of errors
     */
     Element editLink (Element editLink)
            throws SoapFault;


    /**
     * deleteLink Handler.
     *
     * @param deleteLink Request
     * @return deleteLink Response
     * @throws SoapFault In case of errors
     */
     Element deleteLink (Element deleteLink)
            throws SoapFault;


    /**
     * addEndpoint Handler.
     *
     * @param addEndpoint Request
     * @return addEndpoint Response
     * @throws SoapFault In case of errors
     */
     Element addEndpoint (Element addEndpoint)
            throws SoapFault;


    /**
     * getEndpoints Handler.
     *
     * @param getEndpoints Request
     * @return getEndpoints Response
     * @throws SoapFault In case of errors
     */
     Element getEndpoints (Element getEndpoints)
            throws SoapFault;


    /**
     * deleteDomain Handler.
     *
     * @param deleteDomain Request
     * @return deleteDomain Response
     * @throws SoapFault In case of errors
     */
     Element deleteDomain (Element deleteDomain)
            throws SoapFault;


    /**
     * getLinks Handler.
     *
     * @param getLinks Request
     * @return getLinks Response
     * @throws SoapFault In case of errors
     */
     Element getLinks (Element getLinks)
            throws SoapFault;


    /**
     * deleteEndpoint Handler.
     *
     * @param deleteEndpoint Request
     * @return deleteEndpoint Response
     * @throws SoapFault In case of errors
     */
     Element deleteEndpoint (Element deleteEndpoint)
            throws SoapFault;


    /**
     * addOrEditDomain Handler.
     *
     * @param addOrEditDomain Request
     * @return addOrEditDomain Response
     * @throws SoapFault In case of errors
     */
     Element addOrEditDomain (Element addOrEditDomain)
            throws SoapFault;


    /**
     * editDomain Handler.
     *
     * @param editDomain Request
     * @return editDomain Response
     * @throws SoapFault In case of errors
     */
     Element editDomain (Element editDomain)
            throws SoapFault;


    /**
     * editEndpoint Handler.
     *
     * @param editEndpoint Request
     * @return editEndpoint Response
     * @throws SoapFault In case of errors
     */
     Element editEndpoint (Element editEndpoint)
            throws SoapFault;


    /**
     * addDomain Handler.
     *
     * @param addDomain Request
     * @return addDomain Response
     * @throws SoapFault In case of errors
     */
     Element addDomain (Element addDomain)
            throws SoapFault;


    /**
     * getDomains Handler.
     *
     * @param getDomains Request
     * @return getDomains Response
     * @throws SoapFault In case of errors
     */
     Element getDomains (Element getDomains)
            throws SoapFault;


    /**
     * addLink Handler.
     *
     * @param addLink Request
     * @return addLink Response
     * @throws SoapFault In case of errors
     */
     Element addLink (Element addLink)
            throws SoapFault;


}
