package org.opennaas.extensions.idb.serviceinterface.reservation;

import org.apache.muse.core.AbstractCapability;
import org.w3c.dom.Element;

/**
 * reservation server.
 *
 * ReservationWS.java
 * Sat May 12 13:40:43 CEST 2012
 * Generated by the Apache Muse Code Generation Tool
 */
 public class ReservationWS extends AbstractCapability implements IReservationWS {
    /**
     * isAvailable Handler.
     *
     * @param isAvailable Request
     * @return isAvailable Response
     * @throws Exception In case of errors
     */
    public Element isAvailable (final Element isAvailable)
             throws Exception {
        return CommonReservationHandler.getInstance().handle("isAvailable", isAvailable);
    }

    /**
     * activate Handler.
     *
     * @param activate Request
     * @return activate Response
     * @throws Exception In case of errors
     */
    public Element activate (final Element activate)
             throws Exception {
        return CommonReservationHandler.getInstance().handle("activate", activate);
    }

    /**
     * cancelJob Handler.
     *
     * @param cancelJob Request
     * @return cancelJob Response
     * @throws Exception In case of errors
     */
    public Element cancelJob (final Element cancelJob)
             throws Exception {
        return CommonReservationHandler.getInstance().handle("cancelJob", cancelJob);
    }

    /**
     * createReservation Handler.
     *
     * @param createReservation Request
     * @return createReservation Response
     * @throws Exception In case of errors
     */
    public Element createReservation (final Element createReservation)
             throws Exception {
        return CommonReservationHandler.getInstance().handle("createReservation", createReservation);
    }

    /**
     * notification Handler.
     *
     * @param notification Request
     * @return notification Response
     * @throws Exception In case of errors
     */
    public Element notification (final Element notification)
             throws Exception {
        return CommonReservationHandler.getInstance().handle("notification", notification);
    }

    /**
     * bind Handler.
     *
     * @param bind Request
     * @return bind Response
     * @throws Exception In case of errors
     */
    public Element bind (final Element bind)
             throws Exception {
        return CommonReservationHandler.getInstance().handle("bind", bind);
    }

    /**
     * getStatus Handler.
     *
     * @param getStatus Request
     * @return getStatus Response
     * @throws Exception In case of errors
     */
    public Element getStatus (final Element getStatus)
             throws Exception {
        return CommonReservationHandler.getInstance().handle("getStatus", getStatus);
    }

    /**
     * completeJob Handler.
     *
     * @param completeJob Request
     * @return completeJob Response
     * @throws Exception In case of errors
     */
    public Element completeJob (final Element completeJob)
             throws Exception {
        return CommonReservationHandler.getInstance().handle("completeJob", completeJob);
    }

    /**
     * getReservations Handler.
     *
     * @param getReservations Request
     * @return getReservations Response
     * @throws Exception In case of errors
     */
    public Element getReservations (final Element getReservations)
             throws Exception {
        return CommonReservationHandler.getInstance().handle("getReservations", getReservations);
    }

    /**
     * cancelReservation Handler.
     *
     * @param cancelReservation Request
     * @return cancelReservation Response
     * @throws Exception In case of errors
     */
    public Element cancelReservation (final Element cancelReservation)
             throws Exception {
        return CommonReservationHandler.getInstance().handle("cancelReservation", cancelReservation);
    }

    /**
     * getReservation Handler.
     *
     * @param getReservation Request
     * @return getReservation Response
     * @throws Exception In case of errors
     */
    public Element getReservation (final Element getReservation)
             throws Exception {
        return CommonReservationHandler.getInstance().handle("getReservation", getReservation);
    }

}